image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
variables:
  NEW_RELIC_API_KEY: $NEW_RELIC_API_KEY
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/YOUR-STATE-NAME

cache:
  key: YOUR-STATE-NAME
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}

stages:
  - prepare
  - validate
  - build
  - deploy

init:
  stage: prepare
  script:
    - gitlab-terraform init
  only:
    - merge_requests
    - main

validate:
  stage: validate
  script:
    - gitlab-terraform validate
  only:
    - merge_requests
    - main

plan:
  stage: build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  only:
    - merge_requests
    - main

apply:
  stage: deploy
  environment:
    name: production
  script:
    - gitlab-terraform apply
  dependencies:
    - plan
  when: manual
  only:
    - main
